"""initial tables

Revision ID: cbed81e3273c
Revises: 
Create Date: 2026-09-06 19:34:06.236935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbed81e3273c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('references',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('programming_language', sa.Enum('PYTHON', 'JAVASCRIPT', 'JAVA', 'CSHARP', 'RUBY', 'GO', 'PHP', 'CPLUSPLUS', 'SWIFT', 'KOTLIN', name='programminglanguageenum'), nullable=True),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('sub_topic', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('reference_answer', sa.String(), nullable=False),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_references_topic'), 'references', ['topic'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='roleenum'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('programming_language', sa.Enum('PYTHON', 'JAVASCRIPT', 'JAVA', 'CSHARP', 'RUBY', 'GO', 'PHP', 'CPLUSPLUS', 'SWIFT', 'KOTLIN', name='programminglanguageenum'), nullable=False),
    sa.Column('candidate_level', sa.Enum('INTERN', 'FRESHER', 'JUNIOR', 'MID', 'SENIOR', name='candidatelevelenum'), nullable=False),
    sa.Column('personality_type', sa.Enum('STRICT', 'WARM', 'ENGINEERING', 'ACADEMIC', 'SARCASM', 'COACHING', name='personalitytypeenum'), nullable=False),
    sa.Column('correction_mode', sa.Enum('STRICT', 'GUIDED', name='correctionmodeenum'), nullable=False),
    sa.Column('resume_text', sa.String(), nullable=True),
    sa.Column('jd_text', sa.String(), nullable=True),
    sa.Column('stage', sa.Enum('ICE_BREAKER', 'TECHNICAL', 'CODING', 'BEHAVIORAL', 'WRAP_UP', name='stageenum'), nullable=False),
    sa.Column('current_topic', sa.String(), nullable=True),
    sa.Column('focus_topics', sa.JSON(), nullable=True),
    sa.Column('covered_topics', sa.JSON(), nullable=True),
    sa.Column('probe_depth', sa.Integer(), nullable=False),
    sa.Column('consecutive_wrongs', sa.Integer(), nullable=False),
    sa.Column('question_asked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('next_question', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'FINISHED', name='statusenum'), nullable=False),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('sender', sa.Enum('INTERVIEWER', 'CANDIDATE', name='senderenum'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_references_topic'), table_name='references')
    op.drop_table('references')
    # ### end Alembic commands ###
